### ISSUE TITLE
File cannot create directory: /deps/root/lib.  Maybe need administrative privileges.

### ISSUE THREAD

**Issue by DKsupermoon** [zeutro/openabe#1]
Hello,
When I try to install openabe-master on Mac, after the /make steps, it pops out the error:
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /deps/root/include/relic_ec.  Maybe need
  administrative privileges.

make[2]: *** [install] Error 1
make[1]: *** [relic-toolkit-0.4.1h/.built] Error 2

And finally:
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /deps/root/lib.  Maybe need administrative
  privileges.

make[2]: *** [install] Error 1
make[1]: *** [googletest-release-1.8.0/.built] Error 2
make: *** [all] Error 2
 
Any idea about this?

**Comment by jakinyele** [comment]
The fix for this is to do: '. ./env' before 'make'
