### ISSUE TITLE
Ubuntu-based system installation problem

### ISSUE THREAD

**Issue by DKsupermoon** [zeutro/openabe#2]
I tried to install openabe-master on Ubuntu machine, everything is OK at the beginning (make / make test steps). However, after the /sudo make install, there is the error: Makefile:7 *** ZROOT is undefined. Need to source env file: . ./env.  And after trying . ./env there is no difference.
Any hints?

**Comment by jakinyele** [comment]
Try sudo -E make install

Note that -E inherits the ZROOT environment vars of your current user. Will update docs.

**Comment by DKsupermoon** [comment]
OK, thank you.
I tried the sudo -E make install and later still has the error (it works in first several steps ) :

mkdir -p /usr/local
cp -r /home/Desktop/openabe-master/deps/root/lib /usr/local
cp -r /home/Desktop/openabe-master/deps/root/include /usr/local
cp -r /home/Desktop/openabe-master/deps/root/bin /usr/local
mkdir -p /usr/local/bin
cp -r /home/Desktop/openabe-master/root/lib /usr/local
cp -r /home/Desktop/openabe-master/root/include /usr/local
install -m 755 /home/Desktop/openabe-master/src/bench_libopenabe /usr/local/bin
install -m 755 /home/Desktop/openabe-master/src/profile_libopenabe /usr/local/bin
install -m 755 /home/Desktop/openabe-master/cli/oabe_{setup,keygen,enc,dec} /usr/local/bin
install: cannot stat '/home/Desktop/openabe-master/cli/oabe_{setup,keygen,enc,dec}': No such file or directory
Makefile:35: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by jakinyele** [comment]
Ok, good. Can you confirm that the cli tools were built in the cli directory? The last error indicates that you didn't compile those tools

**Comment by DKsupermoon** [comment]
Yes, under the openabe-master/cli folder, it has oabe_{setup, keygen, enc, dec}.exe files and other keygen.cpp/ encrypt.cpp and .sh files.

**Comment by jakinyele** [comment]
So, the binaries are in the cli directory yet you get that error?

**Comment by DKsupermoon** [comment]
Yes, I redo all the commands again with sudo -E options, still has that error.

**Comment by jakinyele** [comment]
Ok, I've updated the Makefile. Please try again and let me know.

**Comment by DKsupermoon** [comment]
I try the new Makefile and now it works. 
Thank you so much!
