### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by fklement** [zeutro/openabe#20]
I want to use openabe for a project of mine.  
Unfortunately I'm not able to get it running when following the instructions in the `README.md`.  

Output:
```console
bison -d -v zparser.yy
zparser.yy:39.1-19: warning: deprecated directive, use ‘%define api.prefix {oabe}’ [-Wdeprecated]
   39 | %name-prefix "oabe"
      | ^~~~~~~~~~~~~~~~~~~
zparser.yy:42.9-27: error: syntax error, unexpected string, expecting identifier
   42 | %define "parser_class_name" {Parser}
      |         ^~~~~~~~~~~~~~~~~~~
zparser.yy:58.1-14: warning: deprecated directive, use ‘%define parse.error verbose’ [-Wdeprecated]
   58 | %error-verbose
      | ^~~~~~~~~~~~~~
zparser.yy: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
make[1]: *** [zparser.o] Error 1
make: *** [src] Error 2
```

What am I doing wrong here?

**Comment by babbadeckl** [comment]
[Bison Documentation](https://www.gnu.org/software/bison/manual/html_node/_0025define-Summary.html) states the following:

        Directive: %define api.parser.class {name}
        Language(s): C++, Java
        Purpose: The name of the parser class.
        Accepted Values: Any valid identifier.
        Default Value: In C++, parser. In Java, YYParser or api.prefixParser (see Java Bison Interface).
        History: Introduced in Bison 3.3 to replace parser_class_name.


in zparser.yy replace "parser_class_name" with api.parser.class

**Comment by fklement** [comment]
Thanks @babbadeckl for pointing that out.  💟 
Now everything is working fine.
