### ISSUE TITLE
Failed build on Centos7 

### ISSUE THREAD

**Issue by zacharywhitley** [zeutro/openabe#24]
Build fails with the following error.

zparser.yy:42.9-24: error: %define variable 'api.parser.class' is not used
 %define api.parser.class {Parser}
         ^^^^^^^^^^^^^^^^
make[1]: *** [zparser.o] Error 1
make[1]: Leaving directory `/home/centos/git/openabe/src'
make: *** [src] Error 2

I have bison 3.0.4 installed. 

Changing api.parser.class to parser_class_name seems to fix the problem.

**Comment by jakinyele** [comment]
thanks @zacharywhitley! Is it possible to do version-specific %define to support older versions of bison in the same source file? Trying to avoid having two different zparser.yy. Thoughts?

**Comment by zacharywhitley** [comment]
I'm still looking around for a solution but here's some background info on the problem https://www.gnu.org/software/bison/manual/html_node/_0025define-Summary.html

"History: Introduced in Bison 3.3 to replace parser_class_name."

Bison 3.3 release notes https://lwn.net/Articles/777594/

> The following variables, mostly related to parsers in Java, have been
> renamed for consistency.  Backward compatibility is ensured, but upgrading
> is recommended.
> 
>     abstract           -> api.parser.abstract
>     annotations        -> api.parser.annotations
>     extends            -> api.parser.extends
>     final              -> api.parser.final
>     implements         -> api.parser.implements
>     parser_class_name  -> api.parser.class
>     public             -> api.parser.public
>     strictfp           -> api.parser.strictfp

**Comment by zacharywhitley** [comment]
It says it's backward compatible so you might be ok just using the old  parser_class_name with newer versions of bison but I don't have a way to test that right now.

**Comment by zacharywhitley** [comment]
I think I've got a solution. I removed the definition from zparser.yy and conditionally pass it in from the make file depending on the OS_FAMILY. It's not an ideal solution since it's testing for the OS and not the actual bison version so it will break when Redhat finally updates bison. It also removes the definition from zparser.yy so you need to know that variable needs to be defined before you call it. I'll but in a PR so you can look it over and decide if it's acceptable.

**Comment by zacharywhitley** [comment]
Or as an alternative you could update function_bison_upgrade to check if ${BISON_VERSION} -ge 3.3 in install_pkgs.sh

I think that's the solution I would vote for.

**Comment by zacharywhitley** [comment]
Ok, I just put in a pull request for an alternate way of solving it that I think is a little better that leaves zparser.yy. I'll leave the two PR's out there and you can pick which one you want if any.

**Comment by jakinyele** [comment]
Thanks again for the PR @zacharywhitley. Just accepted and closing this issue.
