### ISSUE TITLE
Quick Tutorial: CP-ABE example

### ISSUE THREAD

**Issue by DKsupermoon** [zeutro/openabe#3]
Hello,
I tried the CP-ABE example in OpenABE Command-line utilities documentation, and the oabe_setup, oabe_kegen part is OK. But the encryption command has error as below.

./oabe_enc -s CP -p org1 -e "((Doctor or Nurse) and (Floor in (2-5)))" \ -i input.txt -o input.cpabe
Could not open file : iostream error

**Comment by jakinyele** [comment]
You are missing the 'input.txt' file. That input.txt was created automatically in the Makefile but you can substitute with whatever file you want to encrypt.

**Comment by DKsupermoon** [comment]
Hi, I checked the folder again and input.txt is in openabe-master/cli folder and I specify this path for oabe-enc command and still has that error.

**Comment by DKsupermoon** [comment]
OK, I solved this issue and thank you so much!
