### ISSUE TITLE
attribute negation

### ISSUE THREAD

**Issue by bejito** [zeutro/openabe#4]
Attribute negation in policies seem possible in literature.
e.g. (attr1 AND **NOT** attr2)

As far as I have seen, this does not seem to be implemented in OpenABE. 
Is it planned at some point ?

**Comment by suezeu** [comment]
Hello.   If you have a small universe (e.g., number) of attributes, you can simply double the attribute space and encode the negation of an attribute as its own attribute.   We do not currently support the negation of arbitrary attribute strings.

If there is a specific need or interest, you can write us at info@zeutro.com.
