### ISSUE TITLE
ERROR oucur when make install

### ISSUE THREAD

**Issue by git4won** [zeutro/openabe#7]
hello，that's another problem:
the directory `./deps/root/bin` is not created, so I have to create it by myself to avoid this error when execute `make install` :
> cp: cannot stat '/home/won/GitHub/openabe/deps/root/bin': No such file or directory Makefile:32: recipe for target 'install-deps' failed make: *** [install-deps] Error 1

**Comment by suezeu** [comment]
hi, we are not able to re-create your error.   however, if you are installing on ubuntu, use "sudo -E make install" instead of "make install".
